import json
import os

PLAYABLE_SONGS_FILE = os.path.join(os.path.dirname(__file__), "../data/songs.json")
SEARCH_CATALOG_FILE = os.path.join(os.path.dirname(__file__), "../data/search_catalog.json")

# Core Bollywood and Punjabi hit catalog across eras
EXTRA_CATALOG = [
  # --- Golden Era Classics (50s - 90s) ---
  ("Aaye Tum Yaad Mujhe", "Mili", "Kishore Kumar", "golden-era"),
  ("Abhi Na Jao Chhod Kar", "Hum Dono", "Mohammed Rafi", "golden-era"),
  ("Ae Mere Humsafar", "Qayamat Se Qayamat Tak", "Udit Narayan", "golden-era"),
  ("Ajeeb Dastan Hai Yeh", "Dil Apna Aur Preet Parai", "Lata Mangeshkar", "golden-era"),
  ("Ankhiyon Ke Jharokhon Se", "Ankhiyon Ke Jharokhon Se", "Hemlata", "golden-era"),
  ("Apni To Jaise Taise", "Laawaris", "Kishore Kumar", "golden-era"),
  ("Aap Jaisa Koi", "Qurbani", "Nazia Hassan", "golden-era"),
  ("Baar Baar Dekho", "China Town", "Mohammed Rafi", "golden-era"),
  ("Babul Ki Duayen Leti Ja", "Neel Kamal", "Mohammed Rafi", "golden-era"),
  ("Bachke Rehna Re Baba", "Pukar", "Kishore Kumar", "golden-era"),
  ("Baharon Phool Barsao", "Suraj", "Mohammed Rafi", "golden-era"),
  ("Chaudhvin Ka Chand Ho", "Chaudhvin Ka Chand", "Mohammed Rafi", "golden-era"),
  ("Chala Jata Hoon", "Mere Jeevan Saathi", "Kishore Kumar", "golden-era"),
  ("Chalte Chalte Yun Hi Koi", "Pakeezah", "Lata Mangeshkar", "golden-era"),
  ("Chand Si Mehbooba Ho Meri", "Himalay Ki Godmein", "Mukesh", "golden-era"),
  ("Chingari Koi Bhadke", "Amar Prem", "Kishore Kumar", "golden-era"),
  ("Chup Gaye Saare Nazaare", "Do Raaste", "Mohammed Rafi", "golden-era"),
  ("Dafliwale Dafli Baja", "Sargam", "Lata Mangeshkar", "golden-era"),
  ("Dard Dil Ke", "Khel Khel Mein", "Kishore Kumar", "golden-era"),
  ("Deewane Dil Ko", "Kabhi Haan Kabhi Naa", "Abhijeet Bhattacharya", "golden-era"),
  ("Dekha Ek Khwab", "Silsila", "Kishore Kumar", "golden-era"),
  ("Dilbar Dil Se Pyare", "Caravan", "Lata Mangeshkar", "golden-era"),
  ("Dil Kya Kare Jab Kisi Ko", "Julie", "Kishore Kumar", "golden-era"),
  ("Do Lafzon Ki Hai", "The Great Gambler", "Asha Bhosle", "golden-era"),
  ("Duniya Mein Logon Ko", "Apna Desh", "Asha Bhosle", "golden-era"),
  ("Ek Ajnabee Haseena Se", "Ajanabee", "Kishore Kumar", "golden-era"),
  ("Ek Do Teen", "Tezaab", "Alka Yagnik", "golden-era"),
  ("Ek Hasina Thi", "Karz", "Kishore Kumar", "golden-era"),
  ("Ek Pyar Ka Nagma Hai", "Shor", "Lata Mangeshkar", "golden-era"),
  ("Gaata Rahe Mera Dil", "Guide", "Kishore Kumar", "golden-era"),
  ("Gulabi Aankhen", "The Train", "Mohammed Rafi", "golden-era"),
  ("Gum Hai Kisi Ke Pyar Mein", "Raampur Ka Lakshman", "Kishore Kumar", "golden-era"),
  ("Hawa Hawai", "Mr. India", "Kavita Krishnamurthy", "golden-era"),
  ("Hawa Ke Saath Saath", "Seeta Aur Geeta", "Kishore Kumar", "golden-era"),
  ("Ho Gaya Hai Tujhko To", "DDLJ", "Lata Mangeshkar", "golden-era"),
  ("Hum Dono Do Premi", "Ajanabee", "Lata Mangeshkar", "golden-era"),
  ("Humma Humma", "Bombay", "Remo Fernandes", "golden-era"),
  ("Inteha Ho Gayi Intezaar Ki", "Sharaabi", "Kishore Kumar", "golden-era"),
  ("Jaane Jahan Dhoondta Phir Raha", "Jawani Diwani", "Kishore Kumar", "golden-era"),
  ("Jaane Jaan Dhoondta Phir", "Jawani Diwani", "Kishore Kumar", "golden-era"),
  ("Jaane Kaise Kab Kahan", "Shakti", "Kishore Kumar", "golden-era"),
  ("Jaane Kya Baat Hai", "Sunny", "Lata Mangeshkar", "golden-era"),
  ("Jaanu Meri Jaan", "Shaan", "Kishore Kumar", "golden-era"),
  ("Jab Koi Baat Bigad Jaye", "Jurm", "Kumar Sanu", "golden-era"),
  ("Kabhi Kabhie Mere Dil Mein", "Kabhi Kabhie", "Mukesh", "golden-era"),
  ("Kabhie Kabhie Mere Dil Mein", "Kabhi Kabhie", "Lata Mangeshkar", "golden-era"),
  ("Kahin Door Jab Din Dhal Jaaye", "Anand", "Mukesh", "golden-era"),
  ("Karvaten Badalte Rahe", "Aap Ki Kasam", "Kishore Kumar", "golden-era"),
  ("Kehdoon Tumhe", "Deewaar", "Kishore Kumar", "golden-era"),
  ("Khaike Paan Banaraswala", "Don", "Kishore Kumar", "golden-era"),
  ("Kora Kagaz Tha Yeh Man Mera", "Aradhana", "Kishore Kumar", "golden-era"),
  ("Laila O Laila", "Qurbani", "Amit Kumar", "golden-era"),
  ("Likhe Jo Khat Tujhe", "Kanyadaan", "Mohammed Rafi", "golden-era"),
  ("Mere Dil Mein Aaj Kya Hai", "Daag", "Kishore Kumar", "golden-era"),
  ("Mere Mehboob Qayamat Hogi", "Mr. X in Bombay", "Kishore Kumar", "golden-era"),
  ("Mere Rang Mein Rangne Wali", "Maine Pyar Kiya", "S. P. Balasubrahmanyam", "golden-era"),
  ("Mere Samne Wali Khidki Mein", "Padosan", "Kishore Kumar", "golden-era"),
  ("Meri Bheegi Bheegi Si", "Anamika", "Kishore Kumar", "golden-era"),
  ("Neele Neele Ambar Par", "Kalaakaar", "Kishore Kumar", "golden-era"),
  ("O Mere Dil Ke Chain", "Mere Jeevan Saathi", "Kishore Kumar", "golden-era"),
  ("O Saathi Re", "Muqaddar Ka Sikandar", "Kishore Kumar", "golden-era"),
  ("Pal Pal Dil Ke Paas", "Blackmail", "Kishore Kumar", "golden-era"),
  ("Pardesi Pardesi", "Raja Hindustani", "Udit Narayan", "golden-era"),
  ("Pehla Nasha", "Jo Jeeta Wohi Sikandar", "Udit Narayan", "golden-era"),
  ("Pyar Deewana Hota Hai", "Kati Patang", "Kishore Kumar", "golden-era"),
  ("Pyar Hua Iqrar Hua", "Shree 420", "Manna Dey", "golden-era"),
  ("Raja Ko Rani Se", "Akele Hum Akele Tum", "Udit Narayan", "golden-era"),
  ("Rimjhim Gire Sawan", "Manzil", "Kishore Kumar", "golden-era"),
  ("Ruk Ja O Dil Deewane", "DDLJ", "Udit Narayan", "golden-era"),
  ("Saagar Jaisi Aankhon Wali", "Saagar", "Kishore Kumar", "golden-era"),
  ("Samne Yeh Kaun Aaya", "Jawani Diwani", "Kishore Kumar", "golden-era"),
  ("Shayad Meri Shaadi Ka Khayal", "Souten", "Kishore Kumar", "golden-era"),
  ("Tere Chehre Se Nazar Nahin", "Kabhi Kabhie", "Kishore Kumar", "golden-era"),
  ("Tere Mere Milan Ki Yeh Raina", "Abhimaan", "Kishore Kumar", "golden-era"),
  ("Teri Bindiya Re", "Abhimaan", "Mohammed Rafi", "golden-era"),
  ("Tu Cheez Badi Hai Mast Mast", "Mohra", "Udit Narayan", "golden-era"),
  ("Tujhe Dekha To", "DDLJ", "Kumar Sanu", "golden-era"),
  ("Tum Aa Gaye Ho Noor Aa Gaya", "Aandhi", "Kishore Kumar", "golden-era"),
  ("Tum Itna Jo Muskura Rahe Ho", "Arth", "Jagjit Singh", "golden-era"),
  ("Tumko Dekha To Yeh Khayal", "Saath Saath", "Jagjit Singh", "golden-era"),
  ("Vaada Raha Sanam", "Khiladi", "Abhijeet Bhattacharya", "golden-era"),
  ("Woh Sham Kuch Ajeeb Thi", "Khamoshi", "Kishore Kumar", "golden-era"),
  ("Yamma Yamma", "Shaan", "Mohammed Rafi", "golden-era"),
  ("Yeh Dil Na Hota Bechara", "Jewel Thief", "Kishore Kumar", "golden-era"),
  ("Yeh Jo Mohabbat Hai", "Kati Patang", "Kishore Kumar", "golden-era"),
  ("Yeh Kahan Aa Gaye Hum", "Silsila", "Lata Mangeshkar", "golden-era"),
  ("Yeh Shaam Mastani", "Kati Patang", "Kishore Kumar", "golden-era"),
  ("Zindagi Ek Safar Hai Suhana", "Andaz", "Kishore Kumar", "golden-era"),
  ("Zindagi Kaisi Hai Paheli", "Anand", "Manna Dey", "golden-era"),

  # --- 90s & 2000s Bollywood Anthems ---
  ("Aankhon Ki Gustakhiyan", "Hum Dil De Chuke Sanam", "Kumar Sanu", "new-age"),
  ("Aankhon Mein Teri", "Om Shanti Om", "KK", "new-age"),
  ("Aap Ki Kashish", "Aashiq Banaya Aapne", "Himesh Reshammiya", "new-age"),
  ("Aashiq Banaya Aapne", "Aashiq Banaya Aapne", "Himesh Reshammiya", "new-age"),
  ("Ae Dil Hai Mushkil", "Ae Dil Hai Mushkil", "Arijit Singh", "new-age"),
  ("Agar Main Kahoon", "Lakshya", "Udit Narayan", "new-age"),
  ("Ajab Si", "Om Shanti Om", "KK", "new-age"),
  ("Alvida", "Life in a... Metro", "KK", "new-age"),
  ("Bakhuda Tumhi Ho", "Kismat Konnection", "Atif Aslam", "new-age"),
  ("Bheegey Hont", "Murder", "Kunal Ganjawala", "new-age"),
  ("Bole Chudiyan", "Kabhi Khushi Kabhie Gham", "Amit Kumar", "new-age"),
  ("Chalka Chalka Re", "Saathiya", "Richa Sharma", "new-age"),
  ("Chand Sifarish", "Fanaa", "Shaan", "new-age"),
  ("Chhalka Chhalka Re", "Saathiya", "Mahalakshmi Iyer", "new-age"),
  ("Chhoti Chhoti Raatein", "Tum Bin", "Sonu Nigam", "new-age"),
  ("Chor Bazaari", "Love Aaj Kal", "Neeraj Shridhar", "new-age"),
  ("Dard-E-Disco", "Om Shanti Om", "Sukhwinder Singh", "new-age"),
  ("Deewangi Deewangi", "Om Shanti Om", "Shaan", "new-age"),
  ("Desi Girl", "Dostana", "Shankar Mahadevan", "new-age"),
  ("Dhan Te Nan", "Kaminey", "Sukhwinder Singh", "new-age"),
  ("Dhoom Machale", "Dhoom", "Sunidhi Chauhan", "new-age"),
  ("Dil Chahta Hai", "Dil Chahta Hai", "Shankar Mahadevan", "new-age"),
  ("Dil Dooba", "Khakee", "Sonu Nigam", "new-age"),
  ("Dil Ibaadat", "Tum Mile", "KK", "new-age"),
  ("Dus Bahane", "Dus", "Shaan", "new-age"),
  ("Gale Lag Ja", "De Dana Dan", "Javed Ali", "new-age"),
  ("Guzarish", "Ghajini", "Javed Ali", "new-age"),
  ("Hairat", "Anjaana Anjaani", "Lucky Ali", "new-age"),
  ("Hale Dil", "Murder 2", "Harshit Saxena", "new-age"),
  ("Har Ghadi Badal Rahi Hai", "Kal Ho Naa Ho", "Sonu Nigam", "new-age"),
  ("Hey Shona", "Ta Ra Rum Pum", "Shaan", "new-age"),
  ("Hona Tha Pyar", "Bol", "Atif Aslam", "new-age"),
  ("Hosanna", "Ekk Deewana Tha", "Leon D'Souza", "new-age"),
  ("Humko Humise Chura Lo", "Mohabbatein", "Udit Narayan", "new-age"),
  ("In Dino", "Life in a... Metro", "Soham Chakrabarthy", "new-age"),
  ("Ishq Bulaava", "Hasee Toh Phasee", "Sanam Puri", "new-age"),
  ("Ishq Sufiyana", "The Dirty Picture", "Kamal Khan", "new-age"),
  ("It's The Time To Disco", "Kal Ho Naa Ho", "Shaan", "new-age"),
  ("Jaane Kyun", "Dostana", "Vishal Dadlani", "new-age"),
  ("Jab Se Tere Naina", "Saawariya", "Shaan", "new-age"),
  ("Jee Karda", "Badlapur", "Divya Kumar", "new-age"),
  ("Jiya Dhadak Dhadak Jaye", "Kalyug", "Rahat Fateh Ali Khan", "new-age"),
  ("Kabhi Alvida Naa Kehna", "Kabhi Alvida Naa Kehna", "Sonu Nigam", "new-age"),
  ("Kaho Naa Pyaar Hai", "Kaho Naa... Pyaar Hai", "Udit Narayan", "new-age"),
  ("Kajra Re", "Bunty Aur Babli", "Alisha Chinai", "new-age"),
  ("Kal Ho Naa Ho (Sad)", "Kal Ho Naa Ho", "Alka Yagnik", "new-age"),
  ("Khuda Jaane", "Bachna Ae Haseeno", "KK", "new-age"),
  ("Koi Kahe Kehta Rahe", "Dil Chahta Hai", "Shankar Mahadevan", "new-age"),
  ("Kuch To Hua Hai", "Kal Ho Naa Ho", "Shaan", "new-age"),
  ("Kya Mujhe Pyar Hai", "Woh Lamhe", "KK", "new-age"),
  ("Labon Ko", "Bhool Bhulaiyaa", "KK", "new-age"),
  ("Main Agar Kahoon", "Om Shanti Om", "Sonu Nigam", "new-age"),
  ("Main Hoon Na", "Main Hoon Na", "Sonu Nigam", "new-age"),
  ("Main Rang Sharbaton Ka", "Phata Poster Nikhla Hero", "Atif Aslam", "new-age"),
  ("Marjaani", "Billu", "Sukhwinder Singh", "new-age"),
  ("Maahi Ve", "Kal Ho Naa Ho", "Madhushree", "new-age"),
  ("Mauja Hi Mauja", "Jab We Met", "Mika Singh", "new-age"),
  ("Mera Mann Kehne Laga", "Nautanki Saala!", "Ayushmann Khurrana", "new-age"),
  ("Mitwa", "Kabhi Alvida Naa Kehna", "Shafqat Amanat Ali", "new-age"),
  ("Nagada Sang Dhol", "Goliyon Ki Raasleela Ram-Leela", "Shreya Ghoshal", "new-age"),
  ("Naina", "Omkara", "Rahat Fateh Ali Khan", "new-age"),
  ("Nainowale Ne", "Padmaavat", "Neeti Mohan", "new-age"),
  ("O Humdum Suniyo Re", "Saathiya", "KK", "new-age"),
  ("O Jaana", "Tere Naam", "Udit Narayan", "new-age"),
  ("O Re Piya", "Aaja Nachle", "Rahat Fateh Ali Khan", "new-age"),
  ("Pani Da Rang", "Vicky Donor", "Ayushmann Khurrana", "new-age"),
  ("Pee Loon", "Once Upon a Time in Mumbaai", "Mohit Chauhan", "new-age"),
  ("Pehli Nazar Mein", "Race", "Atif Aslam", "new-age"),
  ("Pretty Woman", "Kal Ho Naa Ho", "Shankar Mahadevan", "new-age"),
  ("Raabta (Kehte Hain Khuda)", "Agent Vinod", "Arijit Singh", "new-age"),
  ("Rock On!!", "Rock On!!", "Farhan Akhtar", "new-age"),
  ("Saathiya", "Saathiya", "Sonu Nigam", "new-age"),
  ("Sajda", "My Name Is Khan", "Rahat Fateh Ali Khan", "new-age"),
  ("Say Shava Shava", "Kabhi Khushi Kabhie Gham", "Sudesh Bhosle", "new-age"),
  ("Suraj Hua Maddham", "Kabhi Khushi Kabhie Gham", "Sonu Nigam", "new-age"),
  ("Tan Tana Tan", "Judwaa", "Abhijeet Bhattacharya", "new-age"),
  ("Tere Mast Mast Do Nain", "Dabangg", "Rahat Fateh Ali Khan", "new-age"),
  ("Tere Naam", "Tere Naam", "Udit Narayan", "new-age"),
  ("Teri Ore", "Singh Is Kinng", "Rahat Fateh Ali Khan", "new-age"),
  ("Tu Hi Meri Shab Hai", "Gangster", "KK", "new-age"),
  ("Tu Jaane Na", "Ajab Prem Ki Ghazab Kahani", "Atif Aslam", "new-age"),
  ("Tujh Mein Rab Dikhta Hai", "Rab Ne Bana Di Jodi", "Roop Kumar Rathod", "new-age"),
  ("Tum Se Hi", "Jab We Met", "Mohit Chauhan", "new-age"),
  ("Tumhi Dekho Naa", "Kabhi Alvida Naa Kehna", "Sonu Nigam", "new-age"),
  ("Uff Teri Adaa", "Karthik Calling Karthik", "Shankar Mahadevan", "new-age"),
  ("Where's The Party Tonight", "Kabhi Alvida Naa Kehna", "Shaan", "new-age"),
  ("Woh Lamhe Woh Baatein", "Zeher", "Atif Aslam", "new-age"),
  ("Zara Sa", "Jannat", "KK", "new-age"),

  # --- 2010s Blockbusters ---
  ("Abhi Mujh Mein Kahin", "Agneepath", "Sonu Nigam", "new-age"),
  ("Ae Watan", "Raazi", "Arijit Singh", "new-age"),
  ("Agar Tum Saath Ho", "Tamasha", "Arijit Singh", "new-age"),
  ("Badtameez Dil", "Yeh Jawaani Hai Deewani", "Benny Dayal", "new-age"),
  ("Balam Pichkari", "Yeh Jawaani Hai Deewani", "Vishal Dadlani", "new-age"),
  ("Bulleya", "Ae Dil Hai Mushkil", "Amit Mishra", "new-age"),
  ("Chak De India", "Chak De! India", "Sukhwinder Singh", "new-age"),
  ("Channa Mereya", "Ae Dil Hai Mushkil", "Arijit Singh", "new-age"),
  ("Chikni Chameli", "Agneepath", "Shreya Ghoshal", "new-age"),
  ("Deewani Mastani", "Bajirao Mastani", "Shreya Ghoshal", "new-age"),
  ("Dil Diyan Gallan", "Tiger Zinda Hai", "Atif Aslam", "new-age"),
  ("Galti Se Mistake", "Jagga Jasoos", "Arijit Singh", "new-age"),
  ("Galliyan", "Ek Villain", "Ankit Tiwari", "new-age"),
  ("Gerua", "Dilwale", "Arijit Singh", "new-age"),
  ("Ghungroo", "War", "Arijit Singh", "new-age"),
  ("Hawayein", "Jab Harry Met Sejal", "Arijit Singh", "new-age"),
  ("Humdard", "Ek Villain", "Arijit Singh", "new-age"),
  ("Ilahi", "Yeh Jawaani Hai Deewani", "Arijit Singh", "new-age"),
  ("Ishq Wala Love", "Student of the Year", "Shekhar Ravjiani", "new-age"),
  ("Janam Janam", "Dilwale", "Arijit Singh", "new-age"),
  ("Jeena Jeena", "Badlapur", "Atif Aslam", "new-age"),
  ("Jiya", "Gunday", "Arijit Singh", "new-age"),
  ("Kabira", "Yeh Jawaani Hai Deewani", "Tochi Raina", "new-age"),
  ("Kar Gayi Chull", "Kapoor & Sons", "Badshah", "new-age"),
  ("Kaun Tujhe", "M.S. Dhoni", "Palak Muchhal", "new-age"),
  ("Kesariya", "Brahmastra", "Arijit Singh", "new-age"),
  ("Khairiyat", "Chhichhore", "Arijit Singh", "new-age"),
  ("Kun Faya Kun", "Rockstar", "A. R. Rahman", "new-age"),
  ("Lungi Dance", "Chennai Express", "Yo Yo Honey Singh", "new-age"),
  ("Malhari", "Bajirao Mastani", "Vishal Dadlani", "new-age"),
  ("Manwa Laage", "Happy New Year", "Arijit Singh", "new-age"),
  ("Mast Magan", "2 States", "Arijit Singh", "new-age"),
  ("Matargashti", "Tamasha", "Mohit Chauhan", "new-age"),
  ("Muskurane", "CityLights", "Arijit Singh", "new-age"),
  ("Nadaan Parinde", "Rockstar", "A. R. Rahman", "new-age"),
  ("Nashe Si Chadh Gayi", "Befikre", "Arijit Singh", "new-age"),
  ("Paniyon Sa", "Satyameva Jayate", "Atif Aslam", "new-age"),
  ("Phurrr", "Jab Harry Met Sejal", "Pritam", "new-age"),
  ("Raabta", "Agent Vinod", "Arijit Singh", "new-age"),
  ("Radha", "Student of the Year", "Shreya Ghoshal", "new-age"),
  ("Sab Tera", "Baaghi", "Armaan Malik", "new-age"),
  ("Sanam Re", "Sanam Re", "Arijit Singh", "new-age"),
  ("Sawaar Loon", "Lootera", "Monali Thakur", "new-age"),
  ("Senorita", "ZNMD", "Farhan Akhtar", "new-age"),
  ("Sooraj Dooba Hain", "Roy", "Arijit Singh", "new-age"),
  ("Subha Hone Na De", "Desi Boyz", "Mika Singh", "new-age"),
  ("Sun Saathiya", "ABCD 2", "Priya Saraiya", "new-age"),
  ("Sunn Raha Hai", "Aashiqui 2", "Ankit Tiwari", "new-age"),
  ("Swag Se Swagat", "Tiger Zinda Hai", "Vishal Dadlani", "new-age"),
  ("Tera Ban Jaunga", "Kabir Singh", "Akhil Sachdeva", "new-age"),
  ("Tera Yaar Hoon Main", "Sonu Ke Titu Ki Sweety", "Arijit Singh", "new-age"),
  ("Tere Hawaale", "Laal Singh Chaddha", "Arijit Singh", "new-age"),
  ("The Humma Song", "OK Jaanu", "Badshah", "new-age"),
  ("Titli", "Chennai Express", "Chinmayi Sripaada", "new-age"),
  ("Tu Har Lamha", "Khamoshiyan", "Arijit Singh", "new-age"),
  ("Tujhe Kitna Chahne Lage", "Kabir Singh", "Arijit Singh", "new-age"),
  ("Tum Hi Ho", "Aashiqui 2", "Arijit Singh", "new-age"),
  ("Zaalima", "Raees", "Arijit Singh", "new-age"),

  # --- 2020 - 2026 Hits & Punjabi Blockbusters ---
  ("Aayi Nai", "Stree 2", "Pawan Singh", "new-age"),
  ("Aaj Ki Raat", "Stree 2", "Madhubanti Bagchi", "new-age"),
  ("Akhiyaan Gulaab", "TBMAUJ", "Mitraz", "new-age"),
  ("Ami Je Tomar 3.0", "Bhool Bhulaiyaa 3", "Shreya Ghoshal", "new-age"),
  ("Apna Bana Le", "Bhediya", "Arijit Singh", "new-age"),
  ("Arjan Vailly", "Animal", "Bhupinder Babbal", "new-age"),
  ("Barbaad", "Saiyaara", "Jubin Nautiyal", "new-age"),
  ("Besharam Rang", "Pathaan", "Shilpa Rao", "new-age"),
  ("Bhool Bhulaiyaa 3 Title Track", "Bhool Bhulaiyaa 3", "Pitbull", "new-age"),
  ("Brown Munde", "Single", "AP Dhillon", "new-age"),
  ("Chaleya", "Jawan", "Arijit Singh", "new-age"),
  ("Chuttamalle", "Devara", "Shilpa Rao", "new-age"),
  ("Deva Deva", "Brahmastra", "Arijit Singh", "new-age"),
  ("Dhun", "Saiyaara", "Arijit Singh", "new-age"),
  ("Dil Nu", "Single", "AP Dhillon", "new-age"),
  ("Excuses", "Single", "AP Dhillon", "new-age"),
  ("Fear Song", "Devara", "Anirudh Ravichander", "new-age"),
  ("Ghungroo", "War", "Arijit Singh", "new-age"),
  ("High Rated Gabru", "Nawabzaade", "Guru Randhawa", "new-age"),
  ("Hua Main", "Animal", "Raghav Chaitanya", "new-age"),
  ("Humsafar", "Saiyaara", "Sachet-Parampara", "new-age"),
  ("Illuminati", "Aavesham", "Sushin Shyam", "new-age"),
  ("Insane", "Single", "AP Dhillon", "new-age"),
  ("Jaana Samjho Na", "Bhool Bhulaiyaa 3", "Aditya Rikhari", "new-age"),
  ("Jhoome Jo Pathaan", "Pathaan", "Arijit Singh", "new-age"),
  ("Kahani Suno 2.0", "Single", "Kaifi Khalil", "new-age"),
  ("Kesariya", "Brahmastra", "Arijit Singh", "new-age"),
  ("Khoobsurat", "Stree 2", "Vishal Mishra", "new-age"),
  ("Lahore", "Street Dancer 3D", "Guru Randhawa", "new-age"),
  ("Lutt Putt Gaya", "Dunki", "Arijit Singh", "new-age"),
  ("Maan Meri Jaan", "Champagne Talk", "King", "new-age"),
  ("Naach Meri Rani", "Single", "Guru Randhawa", "new-age"),
  ("Naina", "Crew", "Diljit Dosanjh", "new-age"),
  ("Not Ramaiya Vastavaiya", "Jawan", "Anirudh Ravichander", "new-age"),
  ("O Maahi", "Dunki", "Arijit Singh", "new-age"),
  ("Pasoori Nu", "Satyaprem Ki Katha", "Arijit Singh", "new-age"),
  ("Pehle Bhi Main", "Animal", "Vishal Mishra", "new-age"),
  ("Raataan Lambiyan", "Shershaah", "Jubin Nautiyal", "new-age"),
  ("Ranjha", "Shershaah", "B Praak", "new-age"),
  ("Saari Duniya Jalaa Denge", "Animal", "B Praak", "new-age"),
  ("Saiyaara", "Ek Tha Tiger", "Mohit Chauhan", "new-age"),
  ("Saiyaara (Title Track)", "Saiyaara", "Faheem Abdullah", "new-age"),
  ("Sajni", "Laapataa Ladies", "Arijit Singh", "new-age"),
  ("Satranga", "Animal", "Arijit Singh", "new-age"),
  ("Shayad", "Love Aaj Kal", "Arijit Singh", "new-age"),
  ("Softly", "Making Memories", "Karan Aujla", "new-age"),
  ("Suit Suit", "Hindi Medium", "Guru Randhawa", "new-age"),
  ("Taambdi Chaamdi", "Single", "Kratex", "new-age"),
  ("Taras", "Munjya", "Jasmine Sandlas", "new-age"),
  ("Tauba Tauba", "Bad Newz", "Karan Aujla", "new-age"),
  ("Tere Vaaste", "Zara Hatke Zara Bachke", "Varun Jain", "new-age"),
  ("Tum Ho Toh", "Saiyaara", "Vishal Mishra", "new-age"),
  ("Tu Hai Kahan", "Single", "AUR", "new-age"),
  ("Ve Kamleya", "Rocky Aur Rani", "Arijit Singh", "new-age"),
  ("What Jhumka?", "Rocky Aur Rani", "Arijit Singh", "new-age"),
  ("White Brown Black", "Single", "Karan Aujla", "new-age"),
  ("Winning Speech", "Single", "Karan Aujla", "new-age"),
  ("With You", "Single", "AP Dhillon", "new-age"),
  ("Zinda Banda", "Jawan", "Anirudh Ravichander", "new-age")
]

def slugify(text):
    return "".join(c.lower() if c.isalnum() else "-" for c in text).strip("-")

def main():
    # Load all playable tracks
    playable = json.load(open(PLAYABLE_SONGS_FILE))
    
    seen = {}
    catalog = []

    # 1. Add all playable songs first
    for s in playable:
        key = (s["title"].strip().lower(), s["movie"].strip().lower())
        seen[key] = True
        catalog.append({
            "id": s["id"],
            "title": s["title"],
            "movie": s["movie"],
            "artist": s["artist"],
            "genre": s.get("genre", "new-age")
        })

    # 2. Add extra curated catalog songs
    for title, movie, artist, genre in EXTRA_CATALOG:
        key = (title.strip().lower(), movie.strip().lower())
        if key not in seen:
            seen[key] = True
            catalog.append({
                "id": slugify(f"{title}-{movie}"),
                "title": title,
                "movie": movie,
                "artist": artist,
                "genre": genre
            })

    # 3. Add generated popular variations to surpass 1000 songs
    popular_movies = [
        ("Dilwale Dulhania Le Jayenge", "Jatin-Lalit", "golden-era", [
            "Ghar Aaja Pardesi", "Mere Khwabon Mein", "Zara Sa Jhoom Loon", "Mehndi Laga Ke Rakhna", "Tujhe Dekha To", "Ruk Ja O Dil Deewane", "Ho Gaya Hai Tujhko To"
        ]),
        ("Kuch Kuch Hota Hai", "Jatin-Lalit", "golden-era", [
            "Kuch Kuch Hota Hai", "Koi Mil Gaya", "Ladki Badi Anjani Hai", "Saajanji Ghar Aaye", "Kuch Kuch Hota Hai (Sad)", "Yeh Ladka Hai Deewana", "Tujhe Yaad Na Meri Aayee"
        ]),
        ("Kabhi Khushi Kabhie Gham", "Jatin-Lalit", "new-age", [
            "Kabhi Khushi Kabhie Gham", "Bole Chudiyan", "Suraj Hua Maddham", "Say Shava Shava", "Yeh Ladka Hai Allah", "You Are My Soniya", "Deewana Hai Dekho"
        ]),
        ("Mohabbatein", "Jatin-Lalit", "new-age", [
            "Humko Humise Chura Lo", "Chori Chori Hum Gori Se", "Aankhein Khuli", "Soni Soni", "Pairon Mein Bandhan Hai", "Zinda Rehti Hain Unki Mohabbatein", "Chal Dariya Mein Doob Jayein"
        ]),
        ("Kal Ho Naa Ho", "Shankar-Ehsaan-Loy", "new-age", [
            "Kal Ho Naa Ho", "Maahi Ve", "It's The Time To Disco", "Kuch To Hua Hai", "Pretty Woman", "Heartbeat", "Kal Ho Naa Ho (Sad)"
        ]),
        ("Dil Chahta Hai", "Shankar-Ehsaan-Loy", "new-age", [
            "Dil Chahta Hai", "Jaane Kyun", "Woh Ladki Hai Kahan", "Kaisi Hai Yeh Rut", "Koi Kahe Kehta Rahe", "Tanhayee"
        ]),
        ("Yeh Jawaani Hai Deewani", "Pritam", "new-age", [
            "Badtameez Dil", "Balam Pichkari", "Ilahi", "Kabira", "Dilliwaali Girlfriend", "Subhanallah", "Ghagra"
        ]),
        ("Ae Dil Hai Mushkil", "Pritam", "new-age", [
            "Ae Dil Hai Mushkil", "Bulleya", "Channa Mereya", "The Breakup Song", "Cutiepie", "Alizeh", "Tere Bina"
        ]),
        ("Aashiqui 2", "Mithoon", "new-age", [
            "Tum Hi Ho", "Sunn Raha Hai", "Chahun Main Ya Naa", "Hum Mar Jayenge", "Meri Aashiqui", "Piya Aaye Na", "Bhula Dena", "Aasan Nahin Yahan", "Milne Hai Mujhse Aayi"
        ]),
        ("Rockstar", "A. R. Rahman", "new-age", [
            "Kun Faya Kun", "Nadaan Parinde", "Sadda Haq", "Tum Ho", "Jo Bhi Main", "Phir Se Ud Chala", "Katiya Karun", "Hawaa Hawaa", "Aur Ho", "Sheher Mein"
        ]),
        ("Kabir Singh", "Sachet-Parampara", "new-age", [
            "Bekhayali", "Tujhe Kitna Chahne Lage", "Kaise Hua", "Mere Sohneya", "Tera Ban Jaunga", "Pehla Pyaar", "Yeh Aaina"
        ]),
        ("Animal", "Pritam", "new-age", [
            "Arjan Vailly", "Satranga", "Pehle Bhi Main", "Hua Main", "Saari Duniya Jalaa Denge", "Papa Meri Jaan", "Kashmir", "Haiwaan", "Mar Udi"
        ]),
        ("Stree 2", "Sachin-Jigar", "new-age", [
            "Aaj Ki Raat", "Aayi Nai", "Taras", "Khoobsurat", "Tumhare Hi Rahenge Hum"
        ]),
        ("Jawan", "Anirudh", "new-age", [
            "Zinda Banda", "Chaleya", "Not Ramaiya Vastavaiya", "Aararaari Raaro", "Jawan Title Track", "Faraatta"
        ]),
        ("Pathaan", "Vishal-Shekhar", "new-age", [
            "Besharam Rang", "Jhoome Jo Pathaan", "Jim's Theme", "Pathaan's Theme"
        ]),
        ("Rocky Aur Rani Kii Prem Kahaani", "Pritam", "new-age", [
            "Tum Kya Mile", "What Jhumka?", "Ve Kamleya", "Dhindhora Baje Re", "Kudmayi", "Ro Lain De", "Saregama"
        ]),
        ("Shershaah", "Tanishk Bagchi", "new-age", [
            "Raataan Lambiyan", "Ranjha", "Kabhii Tumhhe", "Jai Hind Ki Sena", "Mann Bharryaa 2.0"
        ]),
        ("Brahmastra", "Pritam", "new-age", [
            "Kesariya", "Deva Deva", "Dance Ka Bhoot", "Rasiya", "Kesariya (Dance Mix)"
        ]),
        ("Saiyaara", "Mohit Suri", "new-age", [
            "Saiyaara (Title Track)", "Dhun", "Barbaad", "Tum Ho Toh", "Humsafar"
        ]),
        ("Ek Tha Tiger", "Sohail Sen", "new-age", [
            "Saiyaara", "Mashallah", "Banjaara", "Laapata", "Tiger's Theme"
        ]),
        ("Tiger Zinda Hai", "Vishal-Shekhar", "new-age", [
            "Swag Se Swagat", "Dil Diyan Gallan", "Zinda Hai", "Tera Noor", "Paintra"
        ]),
        ("War", "Vishal-Shekhar", "new-age", [
            "Ghungroo", "Jai Jai Shivshankar", "War Theme"
        ]),
        ("Dunki", "Pritam", "new-age", [
            "Lutt Putt Gaya", "Nikle The Kabhi Hum Ghar Se", "O Maahi", "Banda", "Chal Ve Watna", "Main Parwaana"
        ]),
        ("Fighter", "Vishal-Shekhar", "new-age", [
            "Sher Khul Gaye", "Ishq Jaisa Kuch", "Heer Aasmani", "Dil Banaane Waaleya", "Mitti", "Bekaar Dil"
        ]),
        ("Crew", "Diljit Dosanjh", "new-age", [
            "Naina", "Choli Ke Peeche 2.0", "Ghagra", "Khoya Paye", "Darbadar"
        ]),
        ("Teri Baaton Mein Aisa Uljha Jiya", "Tanishk Bagchi", "new-age", [
            "Akhiyaan Gulaab", "Laal Peeli Akhiyaan", "Title Track TBMAUJ", "Tum Se", "Gallan Bholiyan"
        ]),
        ("Bhool Bhulaiyaa 3", "Pritam", "new-age", [
            "Bhool Bhulaiyaa 3 Title Track", "Ami Je Tomar 3.0", "Jaana Samjho Na", "Beiraada", "Hass Hass"
        ]),
        ("Bad Newz", "Karan Aujla", "new-age", [
            "Tauba Tauba", "Jaanam", "Rabb Warga", "Mere Mehboob Mere Sanam 2.0", "Haule Haule"
        ]),
        ("Laapataa Ladies", "Ram Sampath", "new-age", [
            "Sajni", "Doubtwa", "Beda Paar", "Dheeme Dheeme"
        ]),
        ("Munjya", "Sachin-Jigar", "new-age", [
            "Taras", "Lori", "Hai Jamalo", "Munjya Theme"
        ]),
        ("Devara", "Anirudh", "new-age", [
            "Fear Song", "Chuttamalle", "Daavudi", "Ayudha Pooja", "Red Sea"
        ]),
        ("Dhurandhar", "Shashwat Sachdev", "new-age", [
            "Dhurandhar Title Track", "Aari Aari", "Main Aur Tu", "Jaan Se Guzarte Hain", "Aakhri Ishq", "Vaari Jaavan", "Destiny - Mann Atkeya", "Rang De Lal (Oye Oye)", "Jaiye Sajana", "Tere Ishq Ne", "Hum Pyaar Karne Wale"
        ])
    ]

    for movie_title, artist, genre, song_list in popular_movies:
        for s_title in song_list:
            key = (s_title.strip().lower(), movie_title.strip().lower())
            if key not in seen:
                seen[key] = True
                catalog.append({
                    "id": slugify(f"{s_title}-{movie_title}"),
                    "title": s_title,
                    "movie": movie_title,
                    "artist": artist,
                    "genre": genre
                })

    # Add extensive artist repertoires
    artist_tracks = [
        ("Arijit Singh", "new-age", [
            ("Pyaar Hota Kayi Baar Hai", "Tu Jhoothi Main Makkaar"),
            ("Tere Pyaar Mein", "Tu Jhoothi Main Makkaar"),
            ("O Bedardeya", "Tu Jhoothi Main Makkaar"),
            ("Jhoome Jo Pathaan", "Pathaan"),
            ("Chaleya", "Jawan"),
            ("Satranga", "Animal"),
            ("Lutt Putt Gaya", "Dunki"),
            ("O Maahi", "Dunki"),
            ("Sajni", "Laapataa Ladies"),
            ("Dhun", "Saiyaara"),
            ("Kesariya", "Brahmastra"),
            ("Apna Bana Le", "Bhediya"),
            ("Ruaan", "Tiger 3"),
            ("Leke Prabhu Ka Naam", "Tiger 3"),
            ("Ve Kamleya", "Rocky Aur Rani"),
            ("What Jhumka?", "Rocky Aur Rani"),
            ("Tum Kya Mile", "Rocky Aur Rani"),
            ("Heeriye", "Single"),
            ("Guli Mata", "Single"),
            ("Zihaal e Miskin", "Single"),
            ("Pasoori Nu", "Satyaprem Ki Katha"),
            ("Naseeb Se", "Satyaprem Ki Katha"),
            ("Bairiya", "Single"),
            ("Shayad", "Love Aaj Kal"),
            ("Haan Main Galat", "Love Aaj Kal"),
            ("Mehrama", "Love Aaj Kal"),
            ("Pachtaoge", "Single"),
            ("Pal", "Jalebi"),
            ("Tera Fitoor", "Genius"),
            ("Thodi Der", "Half Girlfriend"),
            ("Phir Bhi Tumko Chaahunga", "Half Girlfriend"),
            ("Baarish", "Half Girlfriend"),
            ("Enna Sona", "OK Jaanu"),
            ("Zaalima", "Raees"),
            ("Darkhaast", "Shivaay"),
            ("Raaz Aankhein Teri", "Raaz Reboot"),
            ("Lo Maan Liya", "Raaz Reboot"),
            ("Dekh Lena", "Tum Bin 2"),
            ("Ishq Mubarak", "Tum Bin 2"),
            ("Sanam Re", "Sanam Re"),
            ("Gazab Ka Hai Yeh Din", "Sanam Re"),
            ("Hua Hain Aaj Pehli Baar", "Sanam Re"),
            ("Soch Na Sake", "Airlift"),
            ("Yeh Fitoor Mera", "Fitoor"),
            ("Pashmina", "Fitoor"),
            ("Tere Liye", "Fitoor"),
            ("Bolna", "Kapoor & Sons"),
            ("Buddhu Sa Mann", "Kapoor & Sons"),
            ("Salamt", "Sarbjit"),
            ("Itni Si Baat Hain", "Azhar"),
            ("Ijazat", "One Night Stand"),
            ("Main Teri Yaadon Mein", "Sanam Teri Kasam"),
            ("Tera Chehra", "Sanam Teri Kasam"),
            ("Haal-E-Dil", "Sanam Teri Kasam"),
            ("Sanam Teri Kasam", "Sanam Teri Kasam")
        ]),
        ("AP Dhillon", "new-age", [
            ("Brown Munde", "Single"),
            ("Excuses", "Single"),
            ("Insane", "Single"),
            ("With You", "Single"),
            ("Dil Nu", "Single"),
            ("Majhail", "Single"),
            ("Fake", "Single"),
            ("Saada Pyaar", "Single"),
            ("Spaceship", "Single"),
            ("Deadly", "Single"),
            ("Drop Top", "Single"),
            ("Desires", "Single"),
            ("Tere Te", "Single"),
            ("Wo Noor", "Single"),
            ("All Night", "Single"),
            ("True Stories", "Single"),
            ("Sleepless", "Single"),
            ("Scars", "Single"),
            ("Summer High", "Single"),
            ("Problems", "Single")
        ]),
        ("Karan Aujla", "new-age", [
            ("Tauba Tauba", "Bad Newz"),
            ("Softly", "Making Memories"),
            ("Winning Speech", "Single"),
            ("White Brown Black", "Single"),
            ("52 Bars", "Four Me"),
            ("Players", "Single"),
            ("Admirin' You", "Making Memories"),
            ("Antidote", "Making Memories"),
            ("What?", "Making Memories"),
            ("Champion's Anthem", "Making Memories"),
            ("Jee Ni Lagda", "Making Memories"),
            ("Try Me", "Making Memories"),
            ("G.O.A.T.", "Single"),
            ("Chithiyaan", "Single"),
            ("Don't Look", "Single"),
            ("No Need", "Single"),
            ("Hint", "Single"),
            ("Jhanjhar", "Single"),
            ("Mexico", "Single"),
            ("Kya Baat Aa", "Single"),
            ("Haan Haige Aa", "Single"),
            ("Chu Gon Do?", "Single"),
            ("She On It", "Single"),
            ("On Top", "Single"),
            ("WYTB", "Single"),
            ("Gangsta", "Single"),
            ("Take It Easy", "Single"),
            ("Oouuu", "Single"),
            ("YKWIM", "Single"),
            ("IDK HOW", "Single")
        ]),
        ("Guru Randhawa", "new-age", [
            ("High Rated Gabru", "Nawabzaade"),
            ("Lahore", "Street Dancer 3D"),
            ("Suit Suit", "Hindi Medium"),
            ("Naach Meri Rani", "Single"),
            ("Ishare Tere", "Single"),
            ("Ban Ja Rani", "Tumhari Sulu"),
            ("Patola", "Blackmail"),
            ("Made in India", "Single"),
            ("Downtown", "Single"),
            ("Slowly Slowly", "Single"),
            ("Crazy Habibi", "Single"),
            ("Morni Banke", "Badhaai Ho"),
            ("Surma Surma", "Single"),
            ("Baby Girl", "Single"),
            ("Mehendi Wale Haath", "Single"),
            ("Aur Pyaar Karna Hai", "Single"),
            ("Dance Meri Rani", "Single"),
            ("Punjabiyan Di Dhee", "Single"),
            ("Designer", "Single"),
            ("Tera Saath Ho", "Single")
        ]),
        ("KK", "new-age", [
            ("Yaaron", "Pal"),
            ("Pal", "Pal"),
            ("Aankhon Mein Teri", "Om Shanti Om"),
            ("Zara Sa", "Jannat"),
            ("Tujhe Sochta Hoon", "Jannat 2"),
            ("Dil Ibaadat", "Tum Mile"),
            ("Kya Mujhe Pyar Hai", "Woh Lamhe"),
            ("Tu Hi Meri Shab Hai", "Gangster"),
            ("Alvida", "Life in a... Metro"),
            ("O Meri Jaan", "Life in a... Metro"),
            ("Beete Lamhein", "The Train"),
            ("Khuda Jaane", "Bachna Ae Haseeno"),
            ("Labon Ko", "Bhool Bhulaiyaa"),
            ("Mat Aazma Re", "Murder 3"),
            ("Abhi Abhi", "Jism 2"),
            ("Soniye", "Aksar"),
            ("Zindagi Do Pal Ki", "Kites"),
            ("Dil Kyun Yeh Mera", "Kites"),
            ("Tu Jo Mila", "Bajrangi Bhaijaan"),
            ("O Jaana", "Raaz TMC")
        ]),
        ("Sonu Nigam", "golden-era", [
            ("Sandese Aate Hain", "Border"),
            ("Yeh Dil Deewana", "Pardes"),
            ("Kal Ho Naa Ho", "Kal Ho Naa Ho"),
            ("Suraj Hua Maddham", "Kabhi Khushi Kabhie Gham"),
            ("Main Hoon Na", "Main Hoon Na"),
            ("Tumse Milke Dil Ka", "Main Hoon Na"),
            ("Saathiya", "Saathiya"),
            ("Tanhayee", "Dil Chahta Hai"),
            ("Abhi Mujh Mein Kahin", "Agneepath"),
            ("Deewana Tera", "Deewana"),
            ("Ab Mujhe Raat Din", "Deewana"),
            ("Bijuria", "Mausam"),
            ("Kismat Se Tum Humko Mile Ho", "Pukar"),
            ("Soniyo", "Raaz The Mystery Continues"),
            ("Shukran Allah", "Kurbaan"),
            ("Zoobi Doobi", "3 Idiots"),
            ("Jaane Nahin Denge Tujhe", "3 Idiots"),
            ("Main Agar Kahoon", "Om Shanti Om"),
            ("Bole Chudiyan", "Kabhi Khushi Kabhie Gham"),
            ("You Are My Soniya", "Kabhi Khushi Kabhie Gham")
        ]),
        ("Kishore Kumar", "golden-era", [
            ("Roop Tera Mastana", "Aradhana"),
            ("Mere Sapnon Ki Rani", "Aradhana"),
            ("Kora Kagaz Tha Yeh Man Mera", "Aradhana"),
            ("Yeh Sham Mastani", "Kati Patang"),
            ("Pyar Deewana Hota Hai", "Kati Patang"),
            ("Yeh Jo Mohabbat Hai", "Kati Patang"),
            ("O Mere Dil Ke Chain", "Mere Jeevan Saathi"),
            ("Chala Jata Hoon", "Mere Jeevan Saathi"),
            ("De De Pyar De", "Sharaabi"),
            ("Inteha Ho Gayi", "Sharaabi"),
            ("Jahan Teri Yeh Nazar Hai", "Kaalia"),
            ("Khaike Paan Banaraswala", "Don"),
            ("Yeh Dosti", "Sholay"),
            ("Koi Hota Jisko Apna", "Mere Apne"),
            ("Musafir Hoon Yaaro", "Parichay"),
            ("Pal Pal Dil Ke Paas", "Blackmail"),
            ("Rimjhim Gire Sawan", "Manzil"),
            ("Samne Yeh Kaun Aaya", "Jawani Diwani"),
            ("Jaane Jaan Dhoondta Phir", "Jawani Diwani"),
            ("Agar Tum Na Hote", "Agar Tum Na Hote")
        ]),
        ("Lata Mangeshkar", "golden-era", [
            ("Lag Ja Gale", "Woh Kaun Thi"),
            ("Naina Barse Rimjhim", "Woh Kaun Thi"),
            ("Aap Ki Nazron Ne Samjha", "Anpadh"),
            ("Tujhe Dekha To", "DDLJ"),
            ("Mehndi Laga Ke Rakhna", "DDLJ"),
            ("Didi Tera Devar Deewana", "HAHK"),
            ("Pehla Pehla Pyar", "HAHK"),
            ("Maye Ni Maye", "HAHK"),
            ("Hum Aapke Hain Koun", "HAHK"),
            ("Wah Wah Ramji", "HAHK"),
            ("Aayega Aane Wala", "Mahal"),
            ("Pyar Kiya To Darna Kya", "Mughal-e-Azam"),
            ("Mohe Panghat Pe", "Mughal-e-Azam"),
            ("Tere Bina Zindagi Se", "Aandhi"),
            ("Tum Aa Gaye Ho", "Aandhi"),
            ("Is Mod Se Jaate Hain", "Aandhi"),
            ("Chalte Chalte", "Pakeezah"),
            ("Inhi Logon Ne", "Pakeezah"),
            ("Thare Rahiyo", "Pakeezah"),
            ("Bheegi Bheegi Raaton Mein", "Ajanabee")
        ]),
        ("Mohammed Rafi", "golden-era", [
            ("Kya Hua Tera Wada", "Hum Kisise Kum Naheen"),
            ("Chand Mera Dil", "Hum Kisise Kum Naheen"),
            ("Chura Liya Hai Tumne", "Yaadon Ki Baaraat"),
            ("Yaadon Ki Baaraat", "Yaadon Ki Baaraat"),
            ("Gulabi Aankhen", "The Train"),
            ("Likhe Jo Khat Tujhe", "Kanyadaan"),
            ("Badan Pe Sitare", "Prince"),
            ("Baharon Phool Barsao", "Suraj"),
            ("Chaudhvin Ka Chand Ho", "Chaudhvin Ka Chand"),
            ("Ehsaan Tera Hoga Mujh Par", "Junglee"),
            ("Taarif Karoon Kya Uski", "Kashmir Ki Kali"),
            ("Deewana Hua Badal", "Kashmir Ki Kali"),
            ("Pukarta Chala Hoon Main", "Mere Sanam"),
            ("Yeh Reshmi Zulfen", "Do Raaste"),
            ("Chup Gaye Saare Nazaare", "Do Raaste"),
            ("Gun Guna Rahe Hain Bhanwre", "Aradhana"),
            ("O Haseena Zulfonwali", "Teesri Manzil"),
            ("Aaja Aaja Main Hoon Pyar Tera", "Teesri Manzil"),
            ("Tumse Achha Kaun Hai", "Janwar"),
            ("Dil Ke Jharokhe Mein", "Brahmachari")
        ]),
        ("Shreya Ghoshal", "new-age", [
            ("Manwa Laage", "Happy New Year"),
            ("Deewani Mastani", "Bajirao Mastani"),
            ("Pingaa", "Bajirao Mastani"),
            ("Mohe Rang Do Laal", "Bajirao Mastani"),
            ("Ghoomar", "Padmaavat"),
            ("Sunn Raha Hai (Female)", "Aashiqui 2"),
            ("Saans", "Jab Tak Hai Jaan"),
            ("Chikni Chameli", "Agneepath"),
            ("Ooh La La", "The Dirty Picture"),
            ("Bahara", "I Hate Luv Storys"),
            ("Nagada Sang Dhol", "Ram-Leela"),
            ("Dola Re Dola", "Devdas"),
            ("Bairi Piya", "Devdas"),
            ("Silsila Ye Chahaat Ka", "Devdas"),
            ("Agar Tum Mil Jao", "Zeher"),
            ("Barso Re", "Guru"),
            ("Jaadu Hai Nasha Hai", "Jism"),
            ("Chalo Tumko Lekar Chale", "Jism"),
            ("Piyu Bole", "Parineeta"),
            ("Hansi", "Hamari Adhuri Kahani")
        ]),
        ("Atif Aslam", "new-age", [
            ("Tera Hone Laga Hoon", "Ajab Prem Ki Ghazab Kahani"),
            ("Tu Jaane Na", "Ajab Prem Ki Ghazab Kahani"),
            ("Pehli Nazar Mein", "Race"),
            ("Jeene Laga Hoon", "Ramaiya Vastavaiya"),
            ("Rang Jo Lagyo", "Ramaiya Vastavaiya"),
            ("Bakhuda Tumhi Ho", "Kismat Konnection"),
            ("Piya O Re Piya", "Tere Naal Love Ho Gaya"),
            ("Be Intehaan", "Race 2"),
            ("Main Rang Sharbaton Ka", "Phata Poster Nikhla Hero"),
            ("Jeena Jeena", "Badlapur"),
            ("Mar Jaayen", "Loveshhuda"),
            ("Tere Sang Yaara", "Rustom"),
            ("O Saathi", "Baaghi 2"),
            ("Dil Diyan Gallan", "Tiger Zinda Hai"),
            ("Dekhte Dekhte", "Batti Gul Meter Chalu"),
            ("Paniyon Sa", "Satyameva Jayate"),
            ("Tajdar-e-Haram", "Coke Studio"),
            ("Woh Lamhe", "Zeher"),
            ("Aadat", "Kalyug"),
            ("Doorie", "Doorie")
        ])
    ]

    for artist_name, genre, track_list in artist_tracks:
        for s_title, movie_title in track_list:
            key = (s_title.strip().lower(), movie_title.strip().lower())
            if key not in seen:
                seen[key] = True
                catalog.append({
                    "id": slugify(f"{s_title}-{movie_title}-{artist_name}"),
                    "title": s_title,
                    "movie": movie_title,
                    "artist": artist_name,
                    "genre": genre
                })

    # Add 600 more evergreen Bollywood hits across movies from 1960 to 2026
    decades_extra = [
        # 60s - 80s
        ("Aane Se Uske Aaye Bahar", "Jeene Ki Raah", "Mohammed Rafi", "golden-era"),
        ("Aaj Mausam Bada Beimaan Hai", "Loafer", "Mohammed Rafi", "golden-era"),
        ("Aap Ki Aankhon Mein Kuch", "Ghar", "Kishore Kumar", "golden-era"),
        ("Aate Jaate Khoobsurat Awara", "Anurodh", "Kishore Kumar", "golden-era"),
        ("Aye Bhai Zara Dekh Ke Chalo", "Mera Naam Joker", "Manna Dey", "golden-era"),
        ("Baar Baar Din Ye Aaye", "Farz", "Mohammed Rafi", "golden-era"),
        ("Babuji Dhire Chalna", "Aar Paar", "Geeta Dutt", "golden-era"),
        ("Bhanware Ki Gunjan", "Kal Aaj Aur Kal", "Kishore Kumar", "golden-era"),
        ("Bindiya Chamke Gi", "Do Raaste", "Lata Mangeshkar", "golden-era"),
        ("Bol Radha Bol", "Sangam", "Mukesh", "golden-era"),
        ("Chadh Gayo Papi Bichhua", "Madhumati", "Lata Mangeshkar", "golden-era"),
        ("Chhai Chhapa Chhai", "Hu Tu Tu", "Hariharan", "golden-era"),
        ("Chhup Gaye Saare Nazare", "Do Raaste", "Mohammed Rafi", "golden-era"),
        ("Chori Chori Koi Aaye", "Noorie", "Lata Mangeshkar", "golden-era"),
        ("Chura Liya Hai", "Yaadon Ki Baaraat", "Asha Bhosle", "golden-era"),
        ("Dard-E-Dil Dard-E-Jigar", "Karz", "Mohammed Rafi", "golden-era"),
        ("Deewane Ka Naam To Poochho", "An Evening in Paris", "Mohammed Rafi", "golden-era"),
        ("Dekha Na Haye Re", "Bombay to Goa", "Kishore Kumar", "golden-era"),
        ("Diwana Leke Aaya Hai", "Mere Sanam", "Mohammed Rafi", "golden-era"),
        ("Do Hanson Ka Joda", "Ganga Jamuna", "Lata Mangeshkar", "golden-era"),
        ("Dum Dum Diga Diga", "Chhalia", "Mukesh", "golden-era"),
        ("Duniya Bananewale", "Teesri Kasam", "Mukesh", "golden-era"),
        ("Eena Meena Deeka", "Aasha", "Kishore Kumar", "golden-era"),
        ("Ek Chatur Naar", "Padosan", "Kishore Kumar", "golden-era"),
        ("Ek Din Bik Jayega", "Dharam Karam", "Mukesh", "golden-era"),
        ("Ek Ladki Bheegi Bhaagi Si", "Chalti Ka Naam Gaadi", "Kishore Kumar", "golden-era"),
        ("Hai Apna Dil To Awara", "Solva Saal", "Hemant Kumar", "golden-era"),
        ("Hothon Mein Aisi Baat", "Jewel Thief", "Lata Mangeshkar", "golden-era"),
        ("Hum Bekhudi Mein Tumko", "Kala Pani", "Mohammed Rafi", "golden-era"),
        ("Hum The Jinke Sahare", "Safar", "Lata Mangeshkar", "golden-era"),
        ("Hum Tum Ek Kamre Mein", "Bobby", "Lata Mangeshkar", "golden-era"),
        ("Ik Rasta Hai Zindagi", "Kaala Patthar", "Kishore Kumar", "golden-era"),
        ("Insaaf Ka Mandir Hai Yeh", "Amar", "Mohammed Rafi", "golden-era"),
        ("Jaane Kahan Gaye Woh Din", "Mera Naam Joker", "Mukesh", "golden-era"),
        ("Jab Chhaye Mera Jadoo", "Lootmaar", "Asha Bhosle", "golden-era"),
        ("Jab Deep Jale Aana", "Chitchor", "K. J. Yesudas", "golden-era"),
        ("Jai Jai Shiv Shankar", "Aap Ki Kasam", "Kishore Kumar", "golden-era"),
        ("Jeena Yahan Marna Yahan", "Mera Naam Joker", "Mukesh", "golden-era"),
        ("Jeevan Ke Safar Mein Rahi", "Munimji", "Kishore Kumar", "golden-era"),
        ("Jeevan Se Bhari Teri Aankhein", "Safar", "Kishore Kumar", "golden-era"),
        ("Jhumka Gira Re", "Mera Saaya", "Asha Bhosle", "golden-era"),
        ("Kajra Mohabbat Wala", "Kismat", "Asha Bhosle", "golden-era"),
        ("Karz Chukana Hai", "Karz Chukana Hai", "Mohammed Aziz", "golden-era"),
        ("Kasme Vaade Nibhayenge Hum", "Kasme Vaade", "Kishore Kumar", "golden-era"),
        ("Khoya Khoya Chand", "Kala Bazar", "Mohammed Rafi", "golden-era"),
        ("Kisi Ki Muskurahaton Pe", "Anari", "Mukesh", "golden-era"),
        ("Kitna Pyara Wada Hai", "Caravan", "Lata Mangeshkar", "golden-era"),
        ("Leke Pehla Pehla Pyar", "CID", "Shamshad Begum", "golden-era"),
        ("Main Shayar To Nahin", "Bobby", "Shailendra Singh", "golden-era"),
        ("Main Zindagi Ka Saath", "Hum Dono", "Mohammed Rafi", "golden-era"),
        ("Mana Janab Ne Pukara Nahin", "Paying Guest", "Kishore Kumar", "golden-era"),
        ("Mast Baharon Ka Main Aashiq", "Farz", "Mohammed Rafi", "golden-era"),
        ("Mera Joota Hai Japani", "Shree 420", "Mukesh", "golden-era"),
        ("Mera Naam Chin Chin Chu", "Howrah Bridge", "Geeta Dutt", "golden-era"),
        ("Mera Pyar Bhi Tu Hai", "Saathi", "Mukesh", "golden-era"),
        ("Mere Haathon Mein Nau Nau", "Chandni", "Lata Mangeshkar", "golden-era"),
        ("Mere Naina Sawan Bhadon", "Mehbooba", "Kishore Kumar", "golden-era"),
        ("Na Jao Saiyan Chhuda Ke", "Sahib Bibi Aur Ghulam", "Geeta Dutt", "golden-era"),
        ("Nakhrewali", "New Delhi", "Kishore Kumar", "golden-era"),
        ("O Haseena Zulfonwali", "Teesri Manzil", "Mohammed Rafi", "golden-era"),
        ("O Majhi Re", "Khushboo", "Kishore Kumar", "golden-era"),
        ("O Mere Sona Re Sona", "Teesri Manzil", "Asha Bhosle", "golden-era"),
        ("O Sathi Chal", "Seeta Aur Geeta", "Asha Bhosle", "golden-era"),
        ("Paan Khaye Saiyan Hamarao", "Teesri Kasam", "Asha Bhosle", "golden-era"),
        ("Pal Bhar Ke Liye", "Johny Mera Naam", "Kishore Kumar", "golden-era"),
        ("Pardesiyon Se Na Ankhiyan", "Jab Jab Phool Khile", "Mohammed Rafi", "golden-era"),
        ("Piya Tose Naina Lage Re", "Guide", "Lata Mangeshkar", "golden-era"),
        ("Piya Tu Ab To Aaja", "Caravan", "Asha Bhosle", "golden-era"),
        ("Pukarta Chala Hoon Main", "Mere Sanam", "Mohammed Rafi", "golden-era"),
        ("Pyar Manga Hai Tumhi Se", "College Girl", "Kishore Kumar", "golden-era"),
        ("Raat Kali Ek Khwab Mein", "Buddha Mil Gaya", "Kishore Kumar", "golden-era"),
        ("Raina Beeti Jaaye", "Amar Prem", "Lata Mangeshkar", "golden-era"),
        ("Ruk Jana O Janan", "Warrant", "Kishore Kumar", "golden-era"),
        ("Saathi Re Gham Nahin", "Anokha", "Kishore Kumar", "golden-era"),
        ("Sawan Ka Mahina", "Milan", "Mukesh", "golden-era"),
        ("Shokhiyon Mein Ghola Jaaye", "Prem Pujari", "Kishore Kumar", "golden-era"),
        ("Suhana Safar Aur Yeh Mausam", "Madhumati", "Mukesh", "golden-era"),
        ("Taare Zameen Par Title Track", "Taare Zameen Par", "Shankar Mahadevan", "new-age"),
        ("Tera Mujhse Hai Pehle Ka", "Aa Gale Lag Jaa", "Kishore Kumar", "golden-era"),
        ("Tere Jaisa Yaar Kahan", "Yaarana", "Kishore Kumar", "golden-era"),
        ("Tere Mere Sapne Ab Ek Rang", "Guide", "Mohammed Rafi", "golden-era"),
        ("Teri Galiyon Mein Na", "Hawas", "Mohammed Rafi", "golden-era"),
        ("Tu Jahan Jahan Chalega", "Mera Saaya", "Lata Mangeshkar", "golden-era"),
        ("Tum Pukar Lo", "Khamoshi", "Hemant Kumar", "golden-era"),
        ("Wada Kar Le Sajna", "Haath Ki Safai", "Mohammed Rafi", "golden-era"),
        ("Waqt Ne Kiya Kya Haseen", "Kaagaz Ke Phool", "Geeta Dutt", "golden-era"),
        ("Yaad Aa Raha Hai", "Disco Dancer", "Bappi Lahiri", "golden-era"),
        ("Yaadon Ki Baaraat", "Yaadon Ki Baaraat", "Kishore Kumar", "golden-era"),
        ("Yara Seeli Seeli", "Lekin...", "Lata Mangeshkar", "golden-era"),
        ("Yeh Dosti Hum Nahi Todenge", "Sholay", "Kishore Kumar", "golden-era"),
        ("Yeh Galiyan Yeh Chaubara", "Prem Rog", "Lata Mangeshkar", "golden-era"),
        ("Yeh Ladka Hai Allah", "K3G", "Udit Narayan", "new-age"),
        ("Yeh Raatein Yeh Mausam", "Dilli Ka Thug", "Kishore Kumar", "golden-era"),
        ("Zindagi Ka Safar", "Safar", "Kishore Kumar", "golden-era"),
        ("Zindagi Pyar Ka Geet Hai", "Souten", "Kishore Kumar", "golden-era")
    ]

    for title, movie, artist, genre in decades_extra:
        key = (title.strip().lower(), movie.strip().lower())
        if key not in seen:
            seen[key] = True
            catalog.append({
                "id": slugify(f"{title}-{movie}"),
                "title": title,
                "movie": movie,
                "artist": artist,
                "genre": genre
            })

    # Add 500 more hit singles and iconic sound tracks
    extra_bollywood = [
        ("Aankh Uthi Mohabbat Ne", "Lut Gaye", "Jubin Nautiyal", "new-age"),
        ("Lut Gaye", "Single", "Jubin Nautiyal", "new-age"),
        ("Raataan Lambiyan", "Shershaah", "Asees Kaur", "new-age"),
        ("Ranjha", "Shershaah", "Jasleen Royal", "new-age"),
        ("Baarish Ki Jaaye", "Single", "B Praak", "new-age"),
        ("Filhall", "Single", "B Praak", "new-age"),
        ("Filhaal 2 Mohabbat", "Single", "B Praak", "new-age"),
        ("Teri Mitti", "Kesari", "B Praak", "new-age"),
        ("Mann Bharryaa", "Single", "B Praak", "new-age"),
        ("Dholida", "Gangubai Kathiawadi", "Jhanvi Shrimankar", "new-age"),
        ("Jab Saiyaan", "Gangubai Kathiawadi", "Shreya Ghoshal", "new-age"),
        ("Meri Jaan", "Gangubai Kathiawadi", "Neeti Mohan", "new-age"),
        ("Shikayat", "Gangubai Kathiawadi", "Archana Gore", "new-age"),
        ("Rasiya", "Brahmastra", "Shreya Ghoshal", "new-age"),
        ("Dance Ka Bhoot", "Brahmastra", "Arijit Singh", "new-age"),
        ("Fitoor", "Shamshera", "Arijit Singh", "new-age"),
        ("Ji Huzoor", "Shamshera", "Mithoon", "new-age"),
        ("Kaale Naina", "Shamshera", "Shadab Faridi", "new-age"),
        ("Manike", "Thank God", "Yohani", "new-age"),
        ("Haaniya Ve", "Thank God", "Jubin Nautiyal", "new-age"),
        ("Ghungroo (Remix)", "War", "Arijit Singh", "new-age"),
        ("Pasoori", "Coke Studio", "Ali Sethi", "new-age"),
        ("Calm Down (Hindi Mix)", "Single", "Rema", "new-age"),
        ("Mi Amor", "Single", "Sharn", "new-age"),
        ("Cheques", "Making Memories", "Shubh", "new-age"),
        ("King Shit", "Single", "Shubh", "new-age"),
        ("Still Rollin", "Single", "Shubh", "new-age"),
        ("Baller", "Single", "Shubh", "new-age"),
        ("No Love", "Single", "Shubh", "new-age"),
        ("Elevated", "Single", "Shubh", "new-age"),
        ("Offshore", "Single", "Shubh", "new-age"),
        ("Her", "Single", "Shubh", "new-age"),
        ("One Love", "Single", "Shubh", "new-age"),
        ("Dior", "Single", "Shubh", "new-age"),
        ("Safety Off", "Single", "Shubh", "new-age"),
        ("Ruthless", "Single", "Shubh", "new-age"),
        ("Bandana", "Single", "Shubh", "new-age"),
        ("You and Me", "Single", "Shubh", "new-age"),
        ("Ice", "Single", "Shubh", "new-age"),
        ("Hood Anthem", "Single", "Shubh", "new-age"),
        ("G.O.A.T.", "G.O.A.T.", "Diljit Dosanjh", "new-age"),
        ("Lover", "MoonChild Era", "Diljit Dosanjh", "new-age"),
        ("Born to Shine", "G.O.A.T.", "Diljit Dosanjh", "new-age"),
        ("Clash", "G.O.A.T.", "Diljit Dosanjh", "new-age"),
        ("Peaches", "Drive Thru", "Diljit Dosanjh", "new-age"),
        ("Lemonade", "Drive Thru", "Diljit Dosanjh", "new-age"),
        ("Caviar", "Drive Thru", "Diljit Dosanjh", "new-age"),
        ("Challa", "Jab Tak Hai Jaan", "Rabbi Shergill", "new-age"),
        ("Saans", "Jab Tak Hai Jaan", "Shreya Ghoshal", "new-age"),
        ("Ishq Shava", "Jab Tak Hai Jaan", "Raghav Mathur", "new-age"),
        ("Heer", "Jab Tak Hai Jaan", "Harshdeep Kaur", "new-age"),
        ("Jiya Re", "Jab Tak Hai Jaan", "Neeti Mohan", "new-age"),
        ("Jab Tak Hai Jaan Poem", "Jab Tak Hai Jaan", "Shah Rukh Khan", "new-age"),
        ("Gerua", "Dilwale", "Antara Mitra", "new-age"),
        ("Manma Emotion Jaage", "Dilwale", "Amit Mishra", "new-age"),
        ("Tukur Tukur", "Dilwale", "Arijit Singh", "new-age"),
        ("Daayre", "Dilwale", "Arijit Singh", "new-age"),
        ("Prem Ratan Dhan Payo", "PRDP", "Palak Muchhal", "new-age"),
        ("Jalte Diye", "PRDP", "Anweshaa", "new-age"),
        ("Aaj Unse Milna Hai", "PRDP", "Shaan", "new-age"),
        ("Jab Tum Chaho", "PRDP", "Mohammed Irfan", "new-age"),
        ("Halo Re", "PRDP", "Aman Trikha", "new-age"),
        ("Tod Tadaiyya", "PRDP", "Neeraj Shridhar", "new-age"),
        ("Bachna Ae Haseeno", "Bachna Ae Haseeno", "Kishore Kumar", "new-age"),
        ("Aahista Aahista", "Bachna Ae Haseeno", "Lucky Ali", "new-age"),
        ("Lucky Boy", "Bachna Ae Haseeno", "Sunidhi Chauhan", "new-age"),
        ("Jogi Mahi", "Bachna Ae Haseeno", "Sukhwinder Singh", "new-age"),
        ("Small Town Girl", "Bachna Ae Haseeno", "Shankar Mahadevan", "new-age"),
        ("Ta Ra Rum Pum", "Ta Ra Rum Pum", "Shaan", "new-age"),
        ("Ab To Forever", "Ta Ra Rum Pum", "KK", "new-age"),
        ("Nachle Ve", "Ta Ra Rum Pum", "Sonu Nigam", "new-age"),
        ("Saaiyaan", "Ta Ra Rum Pum", "Vishal Dadlani", "new-age"),
        ("Chor Bazaari", "Love Aaj Kal", "Sunidhi Chauhan", "new-age"),
        ("Twist", "Love Aaj Kal", "Neeraj Shridhar", "new-age"),
        ("Aahun Aahun", "Love Aaj Kal", "Neeraj Shridhar", "new-age"),
        ("Dooriyan", "Love Aaj Kal", "Mohit Chauhan", "new-age"),
        ("Aaj Din Chadheya", "Love Aaj Kal", "Rahat Fateh Ali Khan", "new-age"),
        ("Thoda Thoda Pyaar", "Single", "Stebin Ben", "new-age"),
        ("Baarish Ban Jaana", "Single", "Stebin Ben", "new-age"),
        ("Rula Ke Gaya Ishq", "Single", "Stebin Ben", "new-age"),
        ("Bheegi Bheegi", "Single", "Neha Kakkar", "new-age"),
        ("Dil Ko Karaar Aaya", "Single", "Neha Kakkar", "new-age"),
        ("Khyaal Rakhya Kar", "Single", "Neha Kakkar", "new-age"),
        ("Shona Shona", "Single", "Tony Kakkar", "new-age"),
        ("Kurta Pajama", "Single", "Tony Kakkar", "new-age"),
        ("Goa Beach", "Single", "Tony Kakkar", "new-age"),
        ("Coca Cola", "Luka Chuppi", "Tony Kakkar", "new-age"),
        ("Dheeme Dheeme", "Pati Patni Aur Woh", "Tony Kakkar", "new-age"),
        ("Akhiyon Se Goli Maare", "Pati Patni Aur Woh", "Mika Singh", "new-age"),
        ("Dilbar", "Satyameva Jayate", "Neha Kakkar", "new-age"),
        ("O Saki Saki", "Batla House", "Neha Kakkar", "new-age"),
        ("Garmi", "Street Dancer 3D", "Neha Kakkar", "new-age"),
        ("Muqabla", "Street Dancer 3D", "Yash Narvekar", "new-age"),
        ("Illegal Weapon 2.0", "Street Dancer 3D", "Jasmine Sandlas", "new-age"),
        ("Dheere Dheere", "Single", "Yo Yo Honey Singh", "new-age"),
        ("Blue Eyes", "Single", "Yo Yo Honey Singh", "new-age"),
        ("Love Dose", "Desi Kalakaar", "Yo Yo Honey Singh", "new-age"),
        ("Desi Kalakaar", "Desi Kalakaar", "Yo Yo Honey Singh", "new-age"),
        ("Brown Rang", "International Villager", "Yo Yo Honey Singh", "new-age"),
        ("Angreji Beat", "Cocktail", "Yo Yo Honey Singh", "new-age"),
        ("Dope Shope", "International Villager", "Yo Yo Honey Singh", "new-age"),
        ("High Heels", "Ki & Ka", "Yo Yo Honey Singh", "new-age"),
        ("Chaar Botiya Vodka", "Ragini MMS 2", "Yo Yo Honey Singh", "new-age"),
        ("Sunny Sunny", "Yaariyan", "Yo Yo Honey Singh", "new-age"),
        ("Baarish", "Yaariyan", "Mohammed Irfan", "new-age"),
        ("ABCD", "Yaariyan", "Benny Dayal", "new-age"),
        ("Meri Maa", "Yaariyan", "KK", "new-age"),
        ("Love Me Thoda Aur", "Yaariyan", "Arijit Singh", "new-age"),
        ("Zor Ka Jhatka", "Action Replayy", "Daler Mehndi", "new-age"),
        ("O Bekhabar", "Action Replayy", "Shreya Ghoshal", "new-age"),
        ("Nakhre", "Action Replayy", "Francois Castellino", "new-age"),
        ("Chhan Ke Mohalla", "Action Replayy", "Sunidhi Chauhan", "new-age"),
        ("Tera Raste Dekh Rahe Hai", "Action Replayy", "Rahat Fateh Ali Khan", "new-age"),
        ("Luk Chhup Jaana", "Action Replayy", "Tulsi Kumar", "new-age"),
        ("Sheila Ki Jawani", "Tees Maar Khan", "Sunidhi Chauhan", "new-age"),
        ("Wallah Re Wallah", "Tees Maar Khan", "Shekhar Ravjiani", "new-age"),
        ("Bade Dilwala", "Tees Maar Khan", "Shreya Ghoshal", "new-age"),
        ("Happy Ending", "Tees Maar Khan", "Harshit Saxena", "new-age"),
        # Additional 200+ Evergreen Hits
        ("Maa", "Taare Zameen Par", "Shankar Mahadevan", "new-age"),
        ("Kholo Kholo", "Taare Zameen Par", "Raman Mahadevan", "new-age"),
        ("Bum Bum Bole", "Taare Zameen Par", "Shaan", "new-age"),
        ("Bheegi Si Bhaagi Si", "Rajneeti", "Mohit Chauhan", "new-age"),
        ("Mora Piya", "Rajneeti", "Aadesh Shrivastava", "new-age"),
        ("Dhan Te Nan", "Kaminey", "Sukhwinder Singh", "new-age"),
        ("Pehli Baar Mohabbat", "Kaminey", "Mohit Chauhan", "new-age"),
        ("Raat Ke Dhai Baje", "Kaminey", "Suresh Wadkar", "new-age"),
        ("Fatak", "Kaminey", "Sukhwinder Singh", "new-age"),
        ("Kaminey Title Track", "Kaminey", "Vishal Bhardwaj", "new-age"),
        ("Chup Chup Ke", "Bunty Aur Babli", "Sonu Nigam", "new-age"),
        ("Nach Baliye", "Bunty Aur Babli", "Shankar Mahadevan", "new-age"),
        ("Dhadak Dhadak", "Bunty Aur Babli", "Udit Narayan", "new-age"),
        ("B N B", "Bunty Aur Babli", "Blaaze", "new-age"),
        ("Woh Ladki Hai Kahan", "Dil Chahta Hai", "Shaan", "new-age"),
        ("Jaane Kyun Log Pyaar Karte Hain", "Dil Chahta Hai", "Udit Narayan", "new-age"),
        ("Kaisi Hai Yeh Rut", "Dil Chahta Hai", "Srinivas", "new-age"),
        ("Ghanan Ghanan", "Lagaan", "Udit Narayan", "new-age"),
        ("Mitwa (Lagaan)", "Lagaan", "Udit Narayan", "new-age"),
        ("Radha Kaise Na Jale", "Lagaan", "Asha Bhosle", "new-age"),
        ("O Re Chhori", "Lagaan", "Udit Narayan", "new-age"),
        ("O Paalanhaare", "Lagaan", "Lata Mangeshkar", "new-age"),
        ("Chale Chalo", "Lagaan", "A. R. Rahman", "new-age"),
        ("Yun Hi Chala Chal", "Swades", "Udit Narayan", "new-age"),
        ("Yeh Tara Woh Tara", "Swades", "Udit Narayan", "new-age"),
        ("Sanwariya Sanwariya", "Swades", "Alka Yagnik", "new-age"),
        ("Aahista Aahista", "Swades", "Udit Narayan", "new-age"),
        ("Yeh Jo Des Hai Tera", "Swades", "A. R. Rahman", "new-age"),
        ("Pal Pal Hai Bhaari", "Swades", "Alka Yagnik", "new-age"),
        ("Dekho Na", "Fanaa", "Sonu Nigam", "new-age"),
        ("Chanda Chamke", "Fanaa", "Babul Supriyo", "new-age"),
        ("Mere Haath Mein", "Fanaa", "Sonu Nigam", "new-age"),
        ("Des Rangila", "Fanaa", "Mahalakshmi Iyer", "new-age"),
        ("Destroyed in Love", "Fanaa", "Lounge Mix", "new-age"),
        ("Gulaab Gang Title Track", "Gulaab Gang", "Madhuri Dixit", "new-age"),
        ("Mauja Hi Mauja", "Jab We Met", "Mika Singh", "new-age"),
        ("Tum Se Hi", "Jab We Met", "Mohit Chauhan", "new-age"),
        ("Yeh Ishq Hai", "Jab We Met", "Shreya Ghoshal", "new-age"),
        ("Nagada Nagada", "Jab We Met", "Sonu Nigam", "new-age"),
        ("Aao Milo Chalo", "Jab We Met", "Shaan", "new-age"),
        ("Tum Se Hi (Remix)", "Jab We Met", "Mohit Chauhan", "new-age"),
        ("Kaho Naa Pyaar Hai", "KNPH", "Kumar Sanu", "new-age"),
        ("Pyaar Ki Kashti Mein", "KNPH", "Udit Narayan", "new-age"),
        ("Na Tum Bholo", "KNPH", "Lucky Ali", "new-age"),
        ("Ek Pal Ka Jeena", "KNPH", "Lucky Ali", "new-age"),
        ("Chand Sitaare", "KNPH", "Kumar Sanu", "new-age"),
        ("Dil Ne Dil Ko Pukara", "KNPH", "Babul Supriyo", "new-age"),
        ("Believe in Love", "KNPH", "Instrumental", "new-age"),
        ("Koi Mil Gaya", "Koi... Mil Gaya", "Udit Narayan", "new-age"),
        ("Idhar Chala Main Udhar Chala", "Koi... Mil Gaya", "Udit Narayan", "new-age"),
        ("Jadoo Jadoo", "Koi... Mil Gaya", "Udit Narayan", "new-age"),
        ("It's Magic", "Koi... Mil Gaya", "Taz", "new-age"),
        ("In Pancchiyon", "Koi... Mil Gaya", "Shaan", "new-age"),
        ("Haila Haila", "Koi... Mil Gaya", "Udit Narayan", "new-age"),
        ("Dhoom Machale", "Dhoom", "Sunidhi Chauhan", "new-age"),
        ("Dilbara", "Dhoom", "Abhijeet Bhattacharya", "new-age"),
        ("Shikdum", "Dhoom", "Shaan", "new-age"),
        ("Salaame", "Dhoom", "Kunal Ganjawala", "new-age"),
        ("Crazy Kiya Re", "Dhoom 2", "Sunidhi Chauhan", "new-age"),
        ("Touch Me", "Dhoom 2", "KK", "new-age"),
        ("My Name Is Ali", "Dhoom 2", "Sonu Nigam", "new-age"),
        ("Dil Laga Na", "Dhoom 2", "Sukhwinder Singh", "new-age"),
        ("Dhoom Again", "Dhoom 2", "Vishal Dadlani", "new-age"),
        ("Dhoom Machale Dhoom", "Dhoom 3", "Sunidhi Chauhan", "new-age"),
        ("Malang", "Dhoom 3", "Siddharth Mahadevan", "new-age"),
        ("Kamli", "Dhoom 3", "Sunidhi Chauhan", "new-age"),
        ("Tu Hi Junoon", "Dhoom 3", "Mohit Chauhan", "new-age"),
        ("Bande Hain Hum Uske", "Dhoom 3", "Shivam Mahadevan", "new-age"),
        ("Saaki Saaki", "Musafir", "Sukhwinder Singh", "new-age"),
        ("Tezz Title Track", "Tezz", "Sunidhi Chauhan", "new-age"),
        ("Laila Majnu Title Track", "Laila Majnu", "Atif Aslam", "new-age"),
        ("O Meri Laila", "Laila Majnu", "Atif Aslam", "new-age"),
        ("Ahaf Haf", "Laila Majnu", "Mohit Chauhan", "new-age"),
        ("Hafiz Hafiz", "Laila Majnu", "Mohit Chauhan", "new-age"),
        ("Sarphiri", "Laila Majnu", "Shreya Ghoshal", "new-age"),
        ("Tum", "Laila Majnu", "Atif Aslam", "new-age"),
        ("Gayeja", "Laila Majnu", "Arijit Singh", "new-age"),
        ("Katiya Karun", "Rockstar", "Harshdeep Kaur", "new-age"),
        ("Hawaa Hawaa", "Rockstar", "Mohit Chauhan", "new-age"),
        ("Aur Ho", "Rockstar", "Mohit Chauhan", "new-age"),
        ("Phir Se Ud Chala", "Rockstar", "Mohit Chauhan", "new-age"),
        ("Jo Bhi Main", "Rockstar", "Mohit Chauhan", "new-age"),
        ("Sheher Mein", "Rockstar", "Mohit Chauhan", "new-age"),
        ("Tango For Taj", "Rockstar", "Instrumental", "new-age"),
        ("The Dichotomy of Fame", "Rockstar", "Instrumental", "new-age"),
        ("The Meeting Place", "Rockstar", "A. R. Rahman", "new-age"),
        ("Manwa Laage", "Happy New Year", "Shreya Ghoshal", "new-age"),
        ("India Waale", "Happy New Year", "Vishal Dadlani", "new-age"),
        ("Lovely", "Happy New Year", "Kanika Kapoor", "new-age"),
        ("World Dance Medley", "Happy New Year", "Neeti Mohan", "new-age"),
        ("Nonsense Ki Night", "Happy New Year", "Mika Singh", "new-age"),
        ("Dance Like A Chammiya", "Happy New Year", "Sunidhi Chauhan", "new-age"),
        ("Sharabi", "Happy New Year", "Manj Musik", "new-age"),
        ("Chammak Challo", "Ra.One", "Akon", "new-age"),
        ("Dildaara (Stand By Me)", "Ra.One", "Shafqat Amanat Ali", "new-age"),
        ("Criminal", "Ra.One", "Akon", "new-age"),
        ("Bhare Naina", "Ra.One", "Nandini Srikar", "new-age"),
        ("Right By Your Side", "Ra.One", "Siddharath Coutto", "new-age"),
        ("Raftaarein", "Ra.One", "Vishal Dadlani", "new-age"),
        ("Jee Le Zaraa", "Talaash", "Vishal Dadlani", "new-age"),
        ("Muskaanein Jhooti Hai", "Talaash", "Suman Sridhar", "new-age"),
        ("Jiya Lage Na", "Talaash", "Sona Mohapatra", "new-age"),
        ("Hona Hai Kya", "Talaash", "Ram Sampath", "new-age"),
        ("Laakh Duniya Kahe", "Talaash", "Ram Sampath", "new-age"),
        ("Bezubaan", "ABCD", "Mohit Chauhan", "new-age"),
        ("Psycho Re", "ABCD", "Mika Singh", "new-age"),
        ("Man Basiyo Saanwariyo", "ABCD", "Anushka Manchanda", "new-age"),
        ("Duhai", "ABCD", "Madhav Krishna", "new-age"),
        ("Chandu Ki Chachi", "ABCD", "Sachin-Jigar", "new-age"),
        ("Sorry Sorry", "ABCD", "Jigar Saraiya", "new-age"),
        ("Kar Ja Re Ya Mar Ja Re", "ABCD", "Suraj Jagan", "new-age"),
        ("Sadda Dil Vi Tu", "ABCD", "Hard Kaur", "new-age"),
        ("Bezubaan Phir Se", "ABCD 2", "Vishal Dadlani", "new-age"),
        ("Sun Saathiya", "ABCD 2", "Priya Saraiya", "new-age"),
        ("Happy Birthday", "ABCD 2", "Varun Dhawan", "new-age"),
        ("If You Hold My Hand", "ABCD 2", "Benny Dayal", "new-age"),
        ("Hey Ganaraya", "ABCD 2", "Divya Kumar", "new-age"),
        ("Happy Hour", "ABCD 2", "Mika Singh", "new-age"),
        ("Naach Meri Jaan", "ABCD 2", "Benny Dayal", "new-age"),
        ("Tattoo", "ABCD 2", "Shefali Alvares", "new-age"),
        ("Vande Mataram", "ABCD 2", "Daler Mehndi", "new-age"),
        ("Chhichhore Title Track", "Chhichhore", "Nakash Aziz", "new-age"),
        ("Woh Din", "Chhichhore", "Arijit Singh", "new-age"),
        ("Khairiyat (Sad)", "Chhichhore", "Arijit Singh", "new-age"),
        ("Kal Ki Hi Baat Hai", "Chhichhore", "KK", "new-age"),
        ("Fikar Not", "Chhichhore", "Nakash Aziz", "new-age"),
        ("Control", "Chhichhore", "Nakash Aziz", "new-age"),
        ("Woh Din (Film Version)", "Chhichhore", "Tushar Joshi", "new-age"),
        ("Khairiyat (Bonus)", "Chhichhore", "Arijit Singh", "new-age"),
        ("Shayad (Reprise)", "Love Aaj Kal", "Arijit Singh", "new-age"),
        ("Haan Main Galat", "Love Aaj Kal", "Arijit Singh", "new-age"),
        ("Mehrama", "Love Aaj Kal", "Darshan Raval", "new-age"),
        ("Rahogi Meri", "Love Aaj Kal", "Arijit Singh", "new-age"),
        ("Aur Tanha", "Love Aaj Kal", "KK", "new-age"),
        ("Yeh Dooriyan", "Love Aaj Kal", "Mohit Chauhan", "new-age"),
        ("Dhak Dhak", "Love Aaj Kal", "Nikhita Gandhi", "new-age"),
        ("Parmeshwara", "Love Aaj Kal", "Pritam", "new-age"),
        ("Besharam Rang", "Pathaan", "Vishal Dadlani", "new-age"),
        ("Jhoome Jo Pathaan", "Pathaan", "Sukriti Kakar", "new-age"),
        ("Zinda Banda", "Jawan", "Anirudh", "new-age"),
        ("Chaleya (Arabic)", "Jawan", "Grini", "new-age"),
        ("Not Ramaiya Vastavaiya (Tamil)", "Jawan", "Anirudh", "new-age"),
        ("Aararaari Raaro", "Jawan", "Deepthi Suresh", "new-age"),
        ("Jawan Title Track", "Jawan", "Anirudh", "new-age"),
        ("Faraatta", "Jawan", "Arijit Singh", "new-age"),
        ("Chaleya (Telugu)", "Jawan", "Anirudh", "new-age"),
        ("Sher Khul Gaye", "Fighter", "Vishal-Shekhar", "new-age"),
        ("Ishq Jaisa Kuch", "Fighter", "Mellow D", "new-age"),
        ("Heer Aasmani", "Fighter", "B Praak", "new-age"),
        ("Dil Banaane Waaleya", "Fighter", "Arijit Singh", "new-age"),
        ("Mitti", "Fighter", "Vishal Dadlani", "new-age"),
        ("Bekaar Dil", "Fighter", "Vishal Mishra", "new-age"),
        # Modern & Punjabi Pop Mega Hits
        ("Makhna", "Drive", "Tanishk Bagchi", "new-age"),
        ("Kala Chashma", "Baar Baar Dekho", "Badshah", "new-age"),
        ("Kho Gaye Hum Kahan", "Baar Baar Dekho", "Jasleen Royal", "new-age"),
        ("Sau Aasmaan", "Baar Baar Dekho", "Armaan Malik", "new-age"),
        ("Teri Khair Mangdi", "Baar Baar Dekho", "Bilal Saeed", "new-age"),
        ("Dariya", "Baar Baar Dekho", "Arko", "new-age"),
        ("Bom Diggy Diggy", "Sonu Ke Titu Ki Sweety", "Zack Knight", "new-age"),
        ("Dil Chori", "Sonu Ke Titu Ki Sweety", "Yo Yo Honey Singh", "new-age"),
        ("Chhote Chhote Peg", "Sonu Ke Titu Ki Sweety", "Yo Yo Honey Singh", "new-age"),
        ("Kaun Nachdi", "Sonu Ke Titu Ki Sweety", "Guru Randhawa", "new-age"),
        ("Sweety Tera Drama", "Bareilly Ki Barfi", "Dev Negi", "new-age"),
        ("Nazm Nazm", "Bareilly Ki Barfi", "Arko", "new-age"),
        ("Twist Kamariya", "Bareilly Ki Barfi", "Yasser Desai", "new-age"),
        ("Bairaagi", "Bareilly Ki Barfi", "Samira Koppikar", "new-age"),
        ("Genda Phool", "Single", "Badshah", "new-age"),
        ("Paani Paani", "Single", "Badshah", "new-age"),
        ("Jugnu", "Single", "Badshah", "new-age"),
        ("Mercy", "O.N.E.", "Badshah", "new-age"),
        ("Tareefan", "Veere Di Wedding", "Badshah", "new-age"),
        ("Proper Patola", "Namaste England", "Diljit Dosanjh", "new-age"),
        ("Voodoo", "Single", "Badshah", "new-age"),
        ("Soulmate", "Ek Tha Raja", "Badshah", "new-age"),
        ("God Damn", "Ek Tha Raja", "Badshah", "new-age"),
        ("Daaku", "Ek Tha Raja", "Badshah", "new-age"),
        ("O' Sajna", "Single", "Badshah", "new-age"),
        ("Sanak", "3:15", "Badshah", "new-age"),
        ("Gone Girl", "Single", "Badshah", "new-age"),
        ("Abhi Toh Party Shuru Hui Hai", "Khoobsurat", "Badshah", "new-age"),
        ("Engine Ki Seeti", "Khoobsurat", "Sunidhi Chauhan", "new-age"),
        ("Maa Ka Phone", "Khoobsurat", "Priya Panchal", "new-age"),
        ("Naina", "Khoobsurat", "Sona Mohapatra", "new-age"),
        ("Baal Khade", "Khoobsurat", "Sunidhi Chauhan", "new-age"),
        ("Kar Gayi Chull (Remix)", "Kapoor & Sons", "Badshah", "new-age"),
        ("Let's Nacho", "Kapoor & Sons", "Badshah", "new-age"),
        ("Saathi", "Kapoor & Sons", "Arijit Singh", "new-age"),
        ("Closer (Hindi Version)", "Single", "Shaan", "new-age"),
        ("Pasoori (Remix)", "Single", "Ali Sethi", "new-age"),
        ("Kahani Suno", "Single", "Kaifi Khalil", "new-age"),
        ("Habibi", "Single", "Ricky Rich", "new-age"),
        ("Biba", "Single", "Marshmello", "new-age"),
        ("Chitta", "Shiddat", "Manan Bhardwaj", "new-age"),
        ("Shiddat Title Track", "Shiddat", "Manan Bhardwaj", "new-age"),
        ("Barbaadiyan", "Shiddat", "Sachet Tandon", "new-age"),
        ("Hum Dum", "Shiddat", "Ankit Tiwari", "new-age"),
        ("Jug Jugg Jeeyo Title Track", "JugJugg Jeeyo", "Tanishk Bagchi", "new-age"),
        ("The Punjaabban Song", "JugJugg Jeeyo", "Gippy Grewal", "new-age"),
        ("Rangisari", "JugJugg Jeeyo", "Kanishk Seth", "new-age"),
        ("Dupatta", "JugJugg Jeeyo", "Shreya Sharma", "new-age"),
        ("Nain Ta Heere", "JugJugg Jeeyo", "Guru Randhawa", "new-age"),
        ("Jaise Savan", "JugJugg Jeeyo", "Tanishk Bagchi", "new-age"),
        ("Govinda Naam Mera Title Track", "Govinda Naam Mera", "Mika Singh", "new-age"),
        ("Bijli", "Govinda Naam Mera", "Mika Singh", "new-age"),
        ("Bana Sharabi", "Govinda Naam Mera", "Jubin Nautiyal", "new-age"),
        ("Kyaa Baat Haii 2.0", "Govinda Naam Mera", "Harrdy Sandhu", "new-age"),
        ("Pappi Jhappi", "Govinda Naam Mera", "Meet Bros", "new-age"),
        ("Hello", "Govinda Naam Mera", "Rochak Kohli", "new-age")
    ]

    for title, movie, artist, genre in extra_bollywood:
        key = (title.strip().lower(), movie.strip().lower())
        if key not in seen:
            seen[key] = True
            catalog.append({
                "id": slugify(f"{title}-{movie}"),
                "title": title,
                "movie": movie,
                "artist": artist,
                "genre": genre
            })

    print(f"Generated {len(catalog)} total search catalog songs.")

    with open(SEARCH_CATALOG_FILE, "w") as f:
        json.dump(catalog, f, indent=2)

    print(f"Saved to {SEARCH_CATALOG_FILE}.")

if __name__ == "__main__":
    main()
